PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?UniversityLectureLabel ?AcademicDepartmentLabel
WHERE {
  ?SubClassDomain Rel:R6 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P10 ?UniversityLectureLabel .
    ?SubClassRange Property:P43 ?AcademicDepartmentLabel .
  }
}