PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?UniversityStudentLabel ?StudentOrganizationLabel
WHERE {
  ?SubClassDomain Rel:R3 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P2 ?UniversityStudentLabel .
    ?SubClassRange Property:P48 ?StudentOrganizationLabel .
  }
}