PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?ProgramOfStudyLabel ?UniversityCourseLabel
WHERE {
  ?SubClassDomain Rel:R33 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P68 ?ProgramOfStudyLabel .
    ?SubClassRange Property:P54 ?UniversityCourseLabel .
  }
}