PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?SportVenueLabel ?UniversityLabel 
WHERE {
  ?SubClassDomain Rel:R77 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P160 ?SportVenueLabel .
    ?SubClassRange Property:P33 ?UniversityLabel .
  }
}