PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?property ?labelID ?labelEN ?descriptionID ?descriptionEN
WHERE {
  ?property rdf:type <http://www.w3.org/2000/01/rdf-schema#Property> ;
            rdfs:label ?labelID ;
            rdfs:label ?labelEN ;
            rdfs:description ?descriptionID ;
            rdfs:description ?descriptionEN .
  
  FILTER(LANG(?labelID) = "id")
  FILTER(LANG(?labelEN) = "en")
  FILTER(LANG(?descriptionID) = "id")
  FILTER(LANG(?descriptionEN) = "en")
}