PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rel: <http://example.com/fukg/data/Relasi:>
PREFIX subClass: <http://example.com/fukg/SubClass/>

SELECT ?relasi ?domainLabel ?rangeLabel
WHERE {
  ?relasi rdf:type rdf:Property ;
          rdfs:label ?labelRelasi ;
          rdfs:domain ?domain ;
          rdfs:range ?range .
  
  OPTIONAL { ?domain rdfs:label ?domainLabel }
  OPTIONAL { ?range rdfs:label ?rangeLabel }
}