PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?MedicalFacilityLabel ?UniversityStaffLabel 
WHERE {
  ?SubClassDomain Rel:R89 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P175 ?MedicalFacilityLabel .
    ?SubClassRange Property:P18 ?UniversityStaffLabel .
  }
}