PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?ClassroomLabel ?UniversityCourseLabel 
WHERE {
  ?SubClassDomain Rel:R54 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P120 ?ClassroomLabel .
    ?SubClassRange Property:P54 ?UniversityCourseLabel .
  }
}