PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?AlumnusLabel ?StudyOfProgramLabel
WHERE {
  ?SubClassDomain Rel:R10 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P26 ?AlumnusLabel .
    ?SubClassRange Property:P68 ?StudyOfProgramLabel .
  }
}