PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?ArticleLabel ?ScientificJournalLabel 
WHERE {
  ?SubClassDomain Rel:R45 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P105 ?ArticleLabel .
    ?SubClassRange Property:P110 ?ScientificJournalLabel .
  }
}