PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?PublicationLabel ?UniversityLectureLabel 
WHERE {
  ?SubClassDomain Rel:R39 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P95 ?PublicationLabel .
    ?SubClassRange Property:P10 ?UniversityLectureLabel .
  }
}