PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?UniversityLaboratoryLabel ?AcademicDepartmentLabel 
WHERE {
  ?SubClassDomain Rel:R50 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P115 ?UniversityLaboratoryLabel .
    ?SubClassRange Property:P43 ?AcademicDepartmentLabel .
  }
}