PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?MedicalFacilityLabel ?UniversityStudentLabel 
WHERE {
  ?SubClassDomain Rel:R87 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P175 ?MedicalFacilityLabel .
    ?SubClassRange Property:P2 ?UniversityStudentLabel .
  }
}