PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?AcademicDepartmentLabel ?UniversityCourseLabel
WHERE {
  ?SubClassDomain Rel:R14 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P43 ?AcademicDepartmentLabel .
    ?SubClassRange Property:P54 ?UniversityCourseLabel .
  }
}