PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?UniversityLabel ?AcademicDepartmentLabel
WHERE {
  ?SubClassDomain Rel:R22 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P33 ?UniversityLabel .
    ?SubClassRange Property:P43 ?AcademicDepartmentLabel .
  }
}