PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?StudentOrganizationLabel ?FacultyLabel
WHERE {
  ?SubClassDomain Rel:R29 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P48 ?StudentOrganizationLabel .
    ?SubClassRange Property:P38 ?FacultyLabel .
  }
}