PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX Rel: <http://example.com/fukg/data/Relasi:> 
PREFIX Property: <http://example.com/fukg/data/Property:> 

SELECT ?BookLabel ?AcademicLibraryLabel 
WHERE {
  ?SubClassDomain Rel:R42 ?SubClassRange .
  
  OPTIONAL {
    ?SubClassDomain Property:P100 ?BookLabel .
    ?SubClassRange Property:P125 ?AcademicLibraryLabel .
  }
}